# Generated by robomake
# CMake FRC ARM toolchain file
# ---------------------------------------------------------
set(ARM_PREFIX arm-frc-linux-gnueabi)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 3)

# FRC_TOOLCHAIN_ROOT is the path to the root of the FRC toolchain installed location
# You should only set this if you haven't installed it to the default location
if(DEFINED FRC_TOOLCHAIN_ROOT)
    set(CMAKE_C_COMPILER "${FRC_TOOLCHAIN_ROOT}/bin/${ARM_PREFIX}-gcc.exe")
    set(CMAKE_CXX_COMPILER "${FRC_TOOLCHAIN_ROOT}/bin/${ARM_PREFIX}-g++.exe")
elseif(CMAKE_HOST_WIN32)
    set(DRIVE_LETTER "$ENV{homedrive}")

    # This assumes the FRC toolchain is installed at %homedrive%:/frc
    # (On almost every system %homedrive% is C:/)
    set(CMAKE_C_COMPILER "${DRIVE_LETTER}/frc/bin/${ARM_PREFIX}-gcc.exe")
    set(CMAKE_CXX_COMPILER "${DRIVE_LETTER}/frc/bin/${ARM_PREFIX}-g++.exe")
else()
    # As it's UNIX, we'll assume it's on the system path.
    set(CMAKE_C_COMPILER "${ARM_PREFIX}-gcc.exe")
    set(CMAKE_CXX_COMPILER "${ARM_PREFIX}-g++.exe")
endif(DEFINED FRC_TOOLCHAIN_ROOT)

set_PROPERTY(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS TRUE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)