/// Generated by robomake
/// An example subsystem

#include <iostream>
#include <math.h>

#include "subsystems/NumberSubsystem.hpp"

using namespace std;

NumberManager::NumberManager() {
    cout << "Constructor called!" << endl;
}

int NumberManager::pythagoreanTheorm(int a, int b) {
    int a2 = a * a;
    int b2 = b * b;
    double c = sqrt(a2 + b2);
    return round(c);
}