/// Generated by robomake

#include <iostream>

#include "Robot.hpp"
#include "subsystems/NumberSubsystem.hpp"


Robot::Robot() {
	numberManager = new NumberManager();
}

void Robot::RobotInit() {
    // This is just a demonstration of "using" a subsystem.
	std::cout << "Robot Init." << std::endl;
	std::cout << "Calculating C value of 3, 5: " << numberManager->pythagoreanTheorm(3, 5) << std::endl;
}

START_ROBOT_CLASS(Robot)
